sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "react-app"
  env: "ReactApp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-816197042049"
  bucket_path: "react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_KEY